#write a programme to disay T
print("-------------------------------")
print("                |              ")
print("                |              ")
print("                |              ")
print("                |              ")
print("                |              ")
print("                |              ")
print("                |              ")
print("                |              ")